[start]
cmd = "mkdir -p /app/bootstrap/cache /app/storage/framework/sessions /app/storage/framework/views /app/storage/framework/cache/data /app/storage/logs /app/storage/app/public && chmod -R 777 /app/bootstrap/cache /app/storage && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
